### ISSUE TITLE
Gracefully handle invalid bibtex

### ISSUE THREAD

**Issue by chfritz** [SaswatPadhi/prismjs-bibtex#3]
First off, thanks a lot for this great prism extension! I've been using it in an online bibtex editor context and it's been working great for the most part, however I've noticed that it sometimes hangs itself when trying to parse invalid bibtex, which of course happens a lot during editing.

I've been able to reliably reproduce this by starting a bibtex file with:
```
@article{newpaper,
  title=

@article{existing,
  title={my old title}
}
```
Somehow, at this particular moment in editing, the plugin appears to go into an infinite loop, because the tab's CPU goes to 100% and freezes completely.

Any idea whether this can be fixed? Simply punting and giving up would be fine in my context (i.e., only highlight when valid).

**Comment by SaswatPadhi** [comment]
Hi @chfritz,

Thanks for the report and the minimal example.

I tried to reproduce locally, but unfortunately I cannot. I tried two approaches:
- placing your example within a Markdown: `bib` code block
- placing your example within HTML: `<pre><code class='language-bib'> ... </code></pre>`

In both cases, the rendering seemed to terminate and the output looks okay to me:

![Screenshot 2023-06-11 at 21-20-19 JSFiddle - Code Playground](https://github.com/SaswatPadhi/prismjs-bibtex/assets/1577944/cf4b30e1-5d04-4028-94ee-292815467f0a)

Here is a link to the JSFiddle playground: https://jsfiddle.net/tgk8v29u/

I tried the above with PrismJS versions 1.23.0 (last tested version for this plugin) and 1.29.0 (current latest version).

Please let me know more about your environment. If you could provide a link to your page where this issue occurs, that would also be super helpful.

**Comment by chfritz** [comment]
Ah, correction, the error happens when typing the next character. I'm able to reproduce it in the jsfiddle you provided -- very helpful, thanks! -- when using this:
```
@article{newpaper,
  title={

@article{existing,
  title={my old title}
}
```

**Comment by SaswatPadhi** [comment]
Thanks again @chfritz! I was able to reproduce the bug and was able to fix it. While at it, I pushed a few other simplifications & minor fixes as well.

Please see the working example at https://saswat.padhi.me/prismjs-bibtex/broken.html -- shouldn't hang your browser :)

Closing this issue, but please feel free to reopen if this hasn't been adequately resolved.

Thanks and regards.
Saswat

**Comment by chfritz** [comment]
Confirmed. Thanks so much for the quick fix!
